version: "3"
services:
  openvpn-as:
    image: linuxserver/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=479
      - TZ=America/Kentucky/Louisville
      - INTERFACE=eth0 #optional
    volumes:
      - /home/estysdesu/openVPNData/config:/config
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    restart: unless-stopped
